# Generated by Django 5.2.8 on 2026-01-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_loginhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginhistory',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
